version: "3.9"

services:



  webapp:
    restart: always
    #image: danik25/webcollection:latest
    build:
        ./
    #depends_on: 
    #  - sqlserver_db
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:5002"
    ports:
      - "5002:5002"
  